export const homeContent = {
  en: {
    HERO: {
      badge: "Free · No signup · Updated monthly",
      headline: ["Know exactly", "what your", "channel earns."],
      sub: "The most accurate YouTube RPM calculator. Estimate AdSense revenue by niche, geography, video format and retention — in under 5 seconds.",
      cta_primary: { label: "Calculate my earnings", href: "/youtube/revenue-calculator" },
      cta_secondary: { label: "Browse niches", href: "/niches" },
      stats: [
        { value: "21", label: "Niches analysed" },
        { value: "38", label: "Countries covered" },
        { value: "100%", label: "Free forever" },
        { value: "<5s", label: "To get results" },
      ],
    },
    FEATURES: [
      { sym: "◈", title: "21 niches, real RPMs", desc: "Each niche has independently researched base RPMs — not blended averages." },
      { sym: "◉", title: "38 country multipliers", desc: "From US (×2.20) to Vietnam (×0.20) — geography is the biggest lever." },
      { sym: "◐", title: "Mid-roll ad modelling", desc: "Videos ≥8 min unlock mid-rolls. We model the exact revenue lift." },
      { sym: "◑", title: "Retention-adjusted RPM", desc: "Audiences watching past 50% signal quality — your effective RPM reflects it." },
    ],
    HOW_IT_WORKS: [
      { num: "01", title: "Enter your metrics in the fields", desc: "View count, retention rate, and video duration — all factored in Forevault." },
      { num: "02", title: "Pick your niche & country", desc: "21 niches and 38 country tiers, each with calibrated RPM multipliers." },
      { num: "03", title: "Get your earnings estimate", desc: "Mid-roll bonuses, retention bonuses and country multipliers applied automatically." },
      { num: "04", title: "Compare across all niches", desc: "See exactly how your niche ranks against every alternative — instantly." },
    ],
    PROOF: {
      eyebrow: "Accurate RPM benchmarks for",
      more: "+25 niches",
    },
    CALC: {
      badge: "RPM Calculator",
      title: ["Your revenue,", "calculated with precision."],
      sub: "Stop guessing. Our YouTube RPM calculator factors in your niche, country tier, video length and audience retention to deliver the most realistic earnings estimate — not just a rough range.",
      cta: "Open the calculator",
    },
    NICHES: {
      badge: "Niche Finder",
      title: ["Not all niches", "are created equal."],
      sub: "RPM varies from $2.50 to $13.50+ depending on your content category. Our Niche Finder ranks every niche by RPM, saturation and revenue potential — make data-driven decisions before you film.",
      highestLabel: "Highest RPM",
      rangeLabel: "RPM range",
      rangeNote: "Between niches",
      browse: "Browse all niches",
    },
    CTA_SECTION: {
      headline: "Ready to know what your channel is really worth?",
      sub: "Thousands of YouTube creators use Forevault to plan content strategy around real, actionable revenue data — not guesswork. Join them and grow smarter.",
      cta_primary: { label: "Calculate for free", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "Browse all niches", href: "/niches" },
      trust: ["No sign-up required", "100% free", "Updated monthly"],
    },
    MOCKUP: {
      url: "forevault.ink/youtube-revenue-calculator",
      badge: "YouTube",
      title: "Revenue Calculator",
      fields: [
        { label: "Views", val: "1,000,000" },
        { label: "Niche", val: "AI Tools ▾", hl: true },
        { label: "Geography", val: "United States ▾" },
        { label: "Duration", val: "12m 30s" },
      ],
      button: "Calculate earnings →",
      resultLabel: "Estimated earnings",
      resultValue: "$13,850",
      resultAvg: "All-niche avg: $4,210",
      meta: [
        { k: "RPM", v: "$13.85" },
        { k: "Format", v: "Long Form" },
        { k: "Ad slots", v: "1 mid-roll", hl: true },
      ],
      chartTitle: "Niche comparison",
      bars: [
        { label: "AI Tools", pct: 100, active: true },
        { label: "Finance", pct: 78 },
        { label: "Business", pct: 70 },
        { label: "True Crime", pct: 38 },
        { label: "Gaming", pct: 18 },
      ],
      heroEarnings: {
        label: "Estimated earnings",
        value: "$13,850",
        chips: ["AI Tools", "United States"],
      },
      heroNiche: {
        label: "Niche RPM comparison",
        rows: [
          { name: "AI Tools", pct: 100, val: "$13.5" },
          { name: "Business", pct: 78, val: "$10.5" },
          { name: "Gaming", pct: 19, val: "$2.5" },
        ],
      },
      heroRPM: {
        label: "Effective RPM",
        value: "$13.85",
        sub: "US · ×2.20 multiplier",
      },
    },
  },

  fr: {
    HERO: {
      badge: "Gratuit · Sans inscription · Mis à jour chaque mois",
      headline: ["Sachez exactement", "combien votre", "chaîne rapporte."],
      sub: "Le calculateur de RPM YouTube le plus précis. Estimez les revenus AdSense selon la niche, la géographie, le format vidéo et la rétention — en moins de 5 secondes.",
      cta_primary: { label: "Calculer mes revenus", href: "/youtube/revenue-calculator" },
      cta_secondary: { label: "Voir les niches", href: "/niches" },
      stats: [
        { value: "21", label: "Niches analysées" },
        { value: "38", label: "Pays couverts" },
        { value: "100%", label: "Toujours gratuit" },
        { value: "<5s", label: "Pour obtenir le résultat" },
      ],
    },
    FEATURES: [
      { sym: "◈", title: "21 niches, RPM réels", desc: "Chaque niche repose sur des RPM recherchés indépendamment, pas sur une moyenne floue." },
      { sym: "◉", title: "38 multiplicateurs pays", desc: "Des États-Unis (×2.20) au Vietnam (×0.20) — la géographie pèse lourd." },
      { sym: "◐", title: "Modélisation des mid-rolls", desc: "Les vidéos de 8 minutes et plus débloquent les mid-rolls. On modélise le gain exact." },
      { sym: "◑", title: "RPM ajusté à la rétention", desc: "Une audience qui regarde au-delà de 50% signale de la qualité — le RPM effectif s’adapte." },
    ],
    HOW_IT_WORKS: [
      { num: "01", title: "Renseignez vos métriques", desc: "Vues, rétention et durée vidéo — tout est pris en compte dans Forevault." },
      { num: "02", title: "Choisissez votre niche et votre pays", desc: "21 niches et 38 niveaux pays, chacun avec ses multiplicateurs calibrés." },
      { num: "03", title: "Obtenez votre estimation", desc: "Bonus mid-roll, bonus rétention et multiplicateurs pays appliqués automatiquement." },
      { num: "04", title: "Comparez toutes les niches", desc: "Voyez instantanément comment votre niche se positionne face aux autres." },
    ],
    PROOF: {
      eyebrow: "Références RPM fiables pour",
      more: "+25 niches",
    },
    CALC: {
      badge: "Calculateur RPM",
      title: ["Vos revenus,", "calculés avec précision."],
      sub: "Arrêtez de deviner. Notre calculateur YouTube RPM prend en compte votre niche, le pays, la durée de la vidéo et la rétention de l’audience pour fournir une estimation réaliste — pas une fourchette vague.",
      cta: "Ouvrir le calculateur",
    },
    NICHES: {
      badge: "Niche Finder",
      title: ["Toutes les niches", "ne se valent pas."],
      sub: "Le RPM varie de 2,50 $ à 13,50 $+ selon votre catégorie. Notre outil classe chaque niche par RPM, saturation et potentiel de revenus — pour décider avant même de filmer.",
      highestLabel: "RPM le plus haut",
      rangeLabel: "Amplitude RPM",
      rangeNote: "Entre niches",
      browse: "Voir toutes les niches",
    },
    CTA_SECTION: {
      headline: "Prêt à savoir ce que vaut vraiment votre chaîne ?",
      sub: "Des milliers de créateurs utilisent Forevault pour construire leur stratégie de contenu sur des données de revenus réelles — pas sur des suppositions. Rejoignez-les et progressez plus intelligemment.",
      cta_primary: { label: "Calculer gratuitement", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "Voir toutes les niches", href: "/niches" },
      trust: ["Sans inscription", "100% gratuit", "Mis à jour chaque mois"],
    },
    MOCKUP: {
      url: "forevault.ink/youtube-revenue-calculator",
      badge: "YouTube",
      title: "Calculateur de revenus",
      fields: [
        { label: "Vues", val: "1 000 000" },
        { label: "Niche", val: "AI Tools ▾", hl: true },
        { label: "Pays", val: "États-Unis ▾" },
        { label: "Durée", val: "12 min 30 s" },
      ],
      button: "Calculer les revenus →",
      resultLabel: "Revenus estimés",
      resultValue: "13 850 $",
      resultAvg: "Moyenne toutes niches : 4 210 $",
      meta: [
        { k: "RPM", v: "13,85 $" },
        { k: "Format", v: "Long format" },
        { k: "Publicités", v: "1 mid-roll", hl: true },
      ],
      chartTitle: "Comparaison des niches",
      bars: [
        { label: "AI Tools", pct: 100, active: true },
        { label: "Finance", pct: 78 },
        { label: "Business", pct: 70 },
        { label: "True Crime", pct: 38 },
        { label: "Gaming", pct: 18 },
      ],
      heroEarnings: {
        label: "Revenus estimés",
        value: "13 850 $",
        chips: ["AI Tools", "États-Unis"],
      },
      heroNiche: {
        label: "Comparaison des RPM par niche",
        rows: [
          { name: "AI Tools", pct: 100, val: "13,5 $" },
          { name: "Business", pct: 78, val: "10,5 $" },
          { name: "Gaming", pct: 19, val: "2,5 $" },
        ],
      },
      heroRPM: {
        label: "RPM effectif",
        value: "13,85 $",
        sub: "US · multiplicateur ×2,20",
      },
    },
  },

  es: {
    HERO: {
      badge: "Gratis · Sin registro · Actualizado cada mes",
      headline: ["Sabe exactamente", "cuánto gana", "tu canal."],
      sub: "El calculador de RPM de YouTube más preciso. Estima ingresos de AdSense por nicho, geografía, formato y retención — en menos de 5 segundos.",
      cta_primary: { label: "Calcular mis ingresos", href: "/youtube/revenue-calculator" },
      cta_secondary: { label: "Ver nichos", href: "/niches" },
      stats: [
        { value: "21", label: "Nichos analizados" },
        { value: "38", label: "Países cubiertos" },
        { value: "100%", label: "Gratis para siempre" },
        { value: "<5s", label: "Para obtener resultados" },
      ],
    },
    FEATURES: [
      { sym: "◈", title: "21 nichos, RPM reales", desc: "Cada nicho tiene RPM base investigados por separado, no promedios mezclados." },
      { sym: "◉", title: "38 multiplicadores por país", desc: "De EE. UU. (×2.20) a Vietnam (×0.20) — la geografía pesa muchísimo." },
      { sym: "◐", title: "Modelo de mid-roll", desc: "Los videos de 8+ minutos desbloquean mid-rolls. Modelamos el aumento exacto." },
      { sym: "◑", title: "RPM ajustado por retención", desc: "Una audiencia que mira más del 50% indica calidad — tu RPM efectivo lo refleja." },
    ],
    HOW_IT_WORKS: [
      { num: "01", title: "Introduce tus métricas", desc: "Vistas, retención y duración del video — todo se tiene en cuenta en Forevault." },
      { num: "02", title: "Elige nicho y país", desc: "21 nichos y 38 niveles por país, cada uno con multiplicadores calibrados." },
      { num: "03", title: "Obtén tu estimación", desc: "Bonos por mid-roll, retención y país aplicados automáticamente." },
      { num: "04", title: "Compara todos los nichos", desc: "Ves al instante cómo se compara tu nicho con el resto." },
    ],
    PROOF: {
      eyebrow: "Referencias RPM fiables para",
      more: "+25 nichos",
    },
    CALC: {
      badge: "Calculadora RPM",
      title: ["Tus ingresos,", "calculados con precisión."],
      sub: "Deja de adivinar. Nuestra calculadora de RPM de YouTube tiene en cuenta nicho, país, duración y retención para ofrecer una estimación realista.",
      cta: "Abrir calculadora",
    },
    NICHES: {
      badge: "Niche Finder",
      title: ["No todos los nichos", "valen lo mismo."],
      sub: "El RPM va de 2,50 $ a 13,50 $+ según la categoría. Nuestro comparador clasifica nichos por RPM, saturación y potencial de ingresos.",
      highestLabel: "RPM más alto",
      rangeLabel: "Rango RPM",
      rangeNote: "Entre nichos",
      browse: "Ver todos los nichos",
    },
    CTA_SECTION: {
      headline: "¿Listo para saber lo que realmente vale tu canal?",
      sub: "Miles de creadores usan Forevault para planificar su estrategia con datos reales de ingresos, no con suposiciones.",
      cta_primary: { label: "Calcular gratis", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "Ver todos los nichos", href: "/niches" },
      trust: ["Sin registro", "100% gratis", "Actualizado cada mes"],
    },
    MOCKUP: {
      url: "forevault.ink/youtube-revenue-calculator",
      badge: "YouTube",
      title: "Calculadora de ingresos",
      fields: [
        { label: "Vistas", val: "1.000.000" },
        { label: "Nicho", val: "AI Tools ▾", hl: true },
        { label: "País", val: "Estados Unidos ▾" },
        { label: "Duración", val: "12m 30s" },
      ],
      button: "Calcular ingresos →",
      resultLabel: "Ingresos estimados",
      resultValue: "13.850 $",
      resultAvg: "Promedio global: 4.210 $",
      meta: [
        { k: "RPM", v: "13,85 $" },
        { k: "Formato", v: "Largo" },
        { k: "Anuncios", v: "1 mid-roll", hl: true },
      ],
      chartTitle: "Comparación de nichos",
      bars: [
        { label: "AI Tools", pct: 100, active: true },
        { label: "Finance", pct: 78 },
        { label: "Business", pct: 70 },
        { label: "True Crime", pct: 38 },
        { label: "Gaming", pct: 18 },
      ],
      heroEarnings: {
        label: "Ingresos estimados",
        value: "13.850 $",
        chips: ["AI Tools", "Estados Unidos"],
      },
      heroNiche: {
        label: "Comparación de RPM por nicho",
        rows: [
          { name: "AI Tools", pct: 100, val: "13,5 $" },
          { name: "Business", pct: 78, val: "10,5 $" },
          { name: "Gaming", pct: 19, val: "2,5 $" },
        ],
      },
      heroRPM: {
        label: "RPM efectivo",
        value: "13,85 $",
        sub: "EE. UU. · multiplicador ×2,20",
      },
    },
  },

  de: {
    HERO: {
      badge: "Gratis · Kein Signup · Monatlich aktualisiert",
      headline: ["Wissen Sie genau,", "was Ihr Kanal", "verdient."],
      sub: "Der präziseste YouTube-RPM-Rechner. Schätzen Sie AdSense-Einnahmen nach Nische, Geografie, Videoformat und Retention — in unter 5 Sekunden.",
      cta_primary: { label: "Einnahmen berechnen", href: "/youtube/revenue-calculator" },
      cta_secondary: { label: "Nischen ansehen", href: "/niches" },
      stats: [
        { value: "21", label: "Analysierte Nischen" },
        { value: "38", label: "Abgedeckte Länder" },
        { value: "100%", label: "Für immer kostenlos" },
        { value: "<5s", label: "Bis zum Ergebnis" },
      ],
    },
    FEATURES: [
      { sym: "◈", title: "21 Nischen, echte RPMs", desc: "Jede Nische basiert auf separat recherchierten Basis-RPMs — nicht auf gemischten Durchschnittswerten." },
      { sym: "◉", title: "38 Länder-Multiplikatoren", desc: "Von den USA (×2.20) bis Vietnam (×0.20) — Geografie ist der größte Hebel." },
      { sym: "◐", title: "Mid-roll-Modellierung", desc: "Videos ab 8 Minuten schalten Mid-rolls frei. Wir modellieren den exakten Mehrwert." },
      { sym: "◑", title: "Retention-adjustierter RPM", desc: "Zuschauer, die über 50% bleiben, signalisieren Qualität — Ihr effektiver RPM spiegelt das wider." },
    ],
    HOW_IT_WORKS: [
      { num: "01", title: "Metriken eingeben", desc: "Aufrufe, Retention und Videolänge — alles wird berücksichtigt." },
      { num: "02", title: "Nische und Land wählen", desc: "21 Nischen und 38 Länderstufen mit kalibrierten Multiplikatoren." },
      { num: "03", title: "Einnahmen schätzen", desc: "Mid-roll-Boni, Retention-Boni und Länderfaktoren automatisch angewendet." },
      { num: "04", title: "Nischen vergleichen", desc: "Sehen Sie sofort, wie Ihre Nische im Vergleich abschneidet." },
    ],
    PROOF: {
      eyebrow: "Verlässliche RPM-Benchmarks für",
      more: "+25 Nischen",
    },
    CALC: {
      badge: "RPM-Rechner",
      title: ["Ihre Einnahmen,", "präzise berechnet."],
      sub: "Hören Sie auf zu raten. Unser YouTube-RPM-Rechner berücksichtigt Nische, Land, Videolänge und Retention für realistische Schätzungen.",
      cta: "Rechner öffnen",
    },
    NICHES: {
      badge: "Nischen-Finder",
      title: ["Nicht jede Nische", "ist gleich viel wert."],
      sub: "Der RPM liegt je nach Kategorie zwischen 2,50 $ und 13,50 $+. Unser Tool sortiert Nischen nach RPM, Sättigung und Ertragspotenzial.",
      highestLabel: "Höchster RPM",
      rangeLabel: "RPM-Spanne",
      rangeNote: "Zwischen Nischen",
      browse: "Alle Nischen ansehen",
    },
    CTA_SECTION: {
      headline: "Bereit zu wissen, was Ihr Kanal wirklich wert ist?",
      sub: "Tausende Creator nutzen Forevault, um ihre Content-Strategie auf echte Einnahmedaten zu stützen — nicht auf Vermutungen.",
      cta_primary: { label: "Kostenlos berechnen", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "Alle Nischen ansehen", href: "/niches" },
      trust: ["Kein Signup", "100% kostenlos", "Monatlich aktualisiert"],
    },
    MOCKUP: {
      url: "forevault.ink/youtube-revenue-calculator",
      badge: "YouTube",
      title: "Einnahmenrechner",
      fields: [
        { label: "Views", val: "1.000.000" },
        { label: "Nische", val: "AI Tools ▾", hl: true },
        { label: "Land", val: "USA ▾" },
        { label: "Dauer", val: "12m 30s" },
      ],
      button: "Einnahmen berechnen →",
      resultLabel: "Geschätzte Einnahmen",
      resultValue: "13.850 $",
      resultAvg: "Nischen-Durchschnitt: 4.210 $",
      meta: [
        { k: "RPM", v: "13,85 $" },
        { k: "Format", v: "Long Form" },
        { k: "Ads", v: "1 Mid-roll", hl: true },
      ],
      chartTitle: "Nischenvergleich",
      bars: [
        { label: "AI Tools", pct: 100, active: true },
        { label: "Finance", pct: 78 },
        { label: "Business", pct: 70 },
        { label: "True Crime", pct: 38 },
        { label: "Gaming", pct: 18 },
      ],
      heroEarnings: {
        label: "Geschätzte Einnahmen",
        value: "13.850 $",
        chips: ["AI Tools", "USA"],
      },
      heroNiche: {
        label: "Nischen-RPM Vergleich",
        rows: [
          { name: "AI Tools", pct: 100, val: "13,5 $" },
          { name: "Business", pct: 78, val: "10,5 $" },
          { name: "Gaming", pct: 19, val: "2,5 $" },
        ],
      },
      heroRPM: {
        label: "Effektiver RPM",
        value: "13,85 $",
        sub: "USA · Multiplikator ×2,20",
      },
    },
  },

  ja: {
    HERO: {
      badge: "無料 · 登録不要 · 毎月更新",
      headline: ["あなたのチャンネルが", "いくら稼ぐかを", "正確に把握する。"],
      sub: "最も精度の高いYouTube RPM計算機。ニッチ、国、動画形式、視聴維持率からAdSense収益を5秒以内で推定します。",
      cta_primary: { label: "収益を計算する", href: "/youtube/revenue-calculator" },
      cta_secondary: { label: "ニッチを見る", href: "/niches" },
      stats: [
        { value: "21", label: "分析済みニッチ" },
        { value: "38", label: "対応国数" },
        { value: "100%", label: "ずっと無料" },
        { value: "<5s", label: "結果表示まで" },
      ],
    },
    FEATURES: [
      { sym: "◈", title: "21ニッチの実測RPM", desc: "各ニッチごとに独自調査したベースRPMを使用しています。" },
      { sym: "◉", title: "38カ国の係数", desc: "米国(×2.20)からベトナム(×0.20)まで、地域差を反映します。" },
      { sym: "◐", title: "ミッドロールの加算", desc: "8分以上の動画でミッドロールが有効化され、収益上昇を反映します。" },
      { sym: "◑", title: "視聴維持率補正", desc: "50%以上視聴されるほど、実効RPMは高くなります。" },
    ],
    HOW_IT_WORKS: [
      { num: "01", title: "数値を入力する", desc: "再生回数、維持率、動画時間を入力します。" },
      { num: "02", title: "ニッチと国を選ぶ", desc: "21ニッチと38国の係数で計算します。" },
      { num: "03", title: "収益を確認する", desc: "ミッドロール、維持率、国係数を自動反映します。" },
      { num: "04", title: "全ニッチを比較する", desc: "あなたのニッチの位置をすぐに確認できます。" },
    ],
    PROOF: {
      eyebrow: "信頼できるRPM指標:",
      more: "+25ニッチ",
    },
    CALC: {
      badge: "RPM計算機",
      title: ["収益を,", "正確に計算する。"],
      sub: "勘に頼るのはやめましょう。ニッチ、国、動画の長さ、維持率を加味して、現実的な収益を推定します。",
      cta: "計算機を開く",
    },
    NICHES: {
      badge: "ニッチ検索",
      title: ["すべてのニッチが", "同じではない。"],
      sub: "RPMはカテゴリによって2.50ドル〜13.50ドル以上まで変動します。RPM、飽和度、収益性で比較できます。",
      highestLabel: "最高RPM",
      rangeLabel: "RPM差",
      rangeNote: "ニッチ間",
      browse: "全ニッチを見る",
    },
    CTA_SECTION: {
      headline: "あなたのチャンネルの本当の価値を知る準備はできましたか？",
      sub: "多くのYouTuberが、推測ではなく実データでコンテンツ戦略を立てるためにForevaultを使っています。",
      cta_primary: { label: "無料で計算", href: "/youtube/revenue-calculator" },
      cta_secondary: { label: "全ニッチを見る", href: "/niches" },
      trust: ["登録不要", "100%無料", "毎月更新"],
    },
    MOCKUP: {
      url: "forevault.ink/youtube-revenue-calculator",
      badge: "YouTube",
      title: "収益計算機",
      fields: [
        { label: "再生回数", val: "1,000,000" },
        { label: "ニッチ", val: "AI Tools ▾", hl: true },
        { label: "国", val: "アメリカ ▾" },
        { label: "動画長", val: "12分30秒" },
      ],
      button: "収益を計算 →",
      resultLabel: "推定収益",
      resultValue: "$13,850",
      resultAvg: "全ニッチ平均: $4,210",
      meta: [
        { k: "RPM", v: "$13.85" },
        { k: "形式", v: "長尺" },
        { k: "広告", v: "ミッドロール1回", hl: true },
      ],
      chartTitle: "ニッチ比較",
      bars: [
        { label: "AI Tools", pct: 100, active: true },
        { label: "Finance", pct: 78 },
        { label: "Business", pct: 70 },
        { label: "True Crime", pct: 38 },
        { label: "Gaming", pct: 18 },
      ],
      heroEarnings: {
        label: "推定収益",
        value: "$13,850",
        chips: ["AI Tools", "アメリカ"],
      },
      heroNiche: {
        label: "ニッチRPM比較",
        rows: [
          { name: "AI Tools", pct: 100, val: "$13.5" },
          { name: "Business", pct: 78, val: "$10.5" },
          { name: "Gaming", pct: 19, val: "$2.5" },
        ],
      },
      heroRPM: {
        label: "実効RPM",
        value: "$13.85",
        sub: "US · ×2.20 倍率",
      },
    },
  },

  ko: {
    HERO: {
      badge: "무료 · 가입 없음 · 매월 업데이트",
      headline: ["당신의 채널이", "얼마를 버는지", "정확히 확인하세요."],
      sub: "가장 정확한 YouTube RPM 계산기입니다. 니치, 국가, 영상 형식, 시청 유지율을 반영해 AdSense 수익을 5초 안에 추정합니다.",
      cta_primary: { label: "수익 계산하기", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "니치 보기", href: "/niches" },
      stats: [
        { value: "21", label: "분석된 니치" },
        { value: "38", label: "지원 국가" },
        { value: "100%", label: "영구 무료" },
        { value: "<5s", label: "결과 확인 시간" },
      ],
    },
    FEATURES: [
      { sym: "◈", title: "21개 니치, 실제 RPM", desc: "각 니치는 별도로 조사한 기준 RPM을 사용합니다." },
      { sym: "◉", title: "38개국 멀티플라이어", desc: "미국(×2.20)부터 베트남(×0.20)까지 지역 차이를 반영합니다." },
      { sym: "◐", title: "미드롤 광고 반영", desc: "8분 이상 영상의 미드롤 수익 증가를 모델링합니다." },
      { sym: "◑", title: "시청 유지율 보정", desc: "50% 이상 시청되는 고품질 시청자는 실효 RPM을 높입니다." },
    ],
    HOW_IT_WORKS: [
      { num: "01", title: "수치를 입력하세요", desc: "조회수, 유지율, 영상 길이를 입력합니다." },
      { num: "02", title: "니치와 국가를 고르세요", desc: "21개 니치와 38개 국가 티어를 사용합니다." },
      { num: "03", title: "수익을 확인하세요", desc: "미드롤, 유지율, 국가 계수가 자동 반영됩니다." },
      { num: "04", title: "모든 니치를 비교하세요", desc: "어떤 니치가 더 강한지 즉시 비교할 수 있습니다." },
    ],
    PROOF: {
      eyebrow: "신뢰할 수 있는 RPM 기준:",
      more: "+25개 니치",
    },
    CALC: {
      badge: "RPM 계산기",
      title: ["수익을,", "정확하게 계산하세요."],
      sub: "추측을 멈추세요. 니치, 국가, 영상 길이, 시청 유지율을 모두 반영해 현실적인 수익을 추정합니다.",
      cta: "계산기 열기",
    },
    NICHES: {
      badge: "니치 파인더",
      title: ["모든 니치가", "같은 가치는 아닙니다."],
      sub: "RPM은 카테고리에 따라 2.50달러에서 13.50달러 이상까지 달라집니다. RPM, 포화도, 수익성으로 비교하세요.",
      highestLabel: "최고 RPM",
      rangeLabel: "RPM 범위",
      rangeNote: "니치 간",
      browse: "모든 니치 보기",
    },
    CTA_SECTION: {
      headline: "당신의 채널이 실제로 얼마나 가치 있는지 알고 싶나요?",
      sub: "많은 크리에이터가 추측이 아니라 실제 수익 데이터로 전략을 세우기 위해 Forevault를 사용합니다.",
      cta_primary: { label: "무료로 계산", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "모든 니치 보기", href: "/niches" },
      trust: ["가입 불필요", "100% 무료", "매월 업데이트"],
    },
    MOCKUP: {
      url: "forevault.ink/youtube-revenue-calculator",
      badge: "YouTube",
      title: "수익 계산기",
      fields: [
        { label: "조회수", val: "1,000,000" },
        { label: "니치", val: "AI Tools ▾", hl: true },
        { label: "국가", val: "미국 ▾" },
        { label: "영상 길이", val: "12분 30초" },
      ],
      button: "수익 계산 →",
      resultLabel: "예상 수익",
      resultValue: "$13,850",
      resultAvg: "전체 니치 평균: $4,210",
      meta: [
        { k: "RPM", v: "$13.85" },
        { k: "형식", v: "롱폼" },
        { k: "광고", v: "미드롤 1회", hl: true },
      ],
      chartTitle: "니치 비교",
      bars: [
        { label: "AI Tools", pct: 100, active: true },
        { label: "Finance", pct: 78 },
        { label: "Business", pct: 70 },
        { label: "True Crime", pct: 38 },
        { label: "Gaming", pct: 18 },
      ],
      heroEarnings: {
        label: "예상 수익",
        value: "$13,850",
        chips: ["AI Tools", "미국"],
      },
      heroNiche: {
        label: "니치 RPM 비교",
        rows: [
          { name: "AI Tools", pct: 100, val: "$13.5" },
          { name: "Business", pct: 78, val: "$10.5" },
          { name: "Gaming", pct: 19, val: "$2.5" },
        ],
      },
      heroRPM: {
        label: "실효 RPM",
        value: "$13.85",
        sub: "미국 · ×2.20 배수",
      },
    },
  },

  pt: {
    HERO: {
      badge: "Grátis · Sem cadastro · Atualizado mensalmente",
      headline: ["Saiba exatamente", "quanto o seu", "canal ganha."],
      sub: "A calculadora de RPM do YouTube mais precisa. Estime a receita do AdSense por nicho, país, formato e retenção — em menos de 5 segundos.",
      cta_primary: { label: "Calcular meus ganhos", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "Ver nichos", href: "/niches" },
      stats: [
        { value: "21", label: "Nichos analisados" },
        { value: "38", label: "Países cobertos" },
        { value: "100%", label: "Sempre grátis" },
        { value: "<5s", label: "Para ver o resultado" },
      ],
    },
    FEATURES: [
      { sym: "◈", title: "21 nichos, RPM reais", desc: "Cada nicho usa RPM base pesquisado individualmente." },
      { sym: "◉", title: "38 multiplicadores por país", desc: "Dos EUA (×2.20) ao Vietnã (×0.20) — geografia pesa muito." },
      { sym: "◐", title: "Modelo de mid-roll", desc: "Vídeos com 8 minutos ou mais desbloqueiam mid-rolls." },
      { sym: "◑", title: "RPM ajustado à retenção", desc: "Quando a audiência passa de 50%, o RPM efetivo sobe." },
    ],
    HOW_IT_WORKS: [
      { num: "01", title: "Insira suas métricas", desc: "Views, retenção e duração do vídeo são considerados." },
      { num: "02", title: "Escolha nicho e país", desc: "21 nichos e 38 níveis por país com multiplicadores calibrados." },
      { num: "03", title: "Veja sua estimativa", desc: "Mid-roll, retenção e país aplicados automaticamente." },
      { num: "04", title: "Compare todos os nichos", desc: "Veja na hora como o seu nicho se posiciona." },
    ],
    PROOF: {
      eyebrow: "Benchmarks de RPM confiáveis para",
      more: "+25 nichos",
    },
    CALC: {
      badge: "Calculadora de RPM",
      title: ["Sua receita,", "calculada com precisão."],
      sub: "Pare de adivinhar. Nossa calculadora de RPM do YouTube considera nicho, país, duração do vídeo e retenção para entregar uma estimativa realista.",
      cta: "Abrir calculadora",
    },
    NICHES: {
      badge: "Niche Finder",
      title: ["Nem todo nicho", "vale o mesmo."],
      sub: "O RPM varia de US$ 2,50 a US$ 13,50+ dependendo da categoria. Compare nichos por RPM, saturação e potencial de receita.",
      highestLabel: "Maior RPM",
      rangeLabel: "Faixa de RPM",
      rangeNote: "Entre nichos",
      browse: "Ver todos os nichos",
    },
    CTA_SECTION: {
      headline: "Pronto para saber quanto o seu canal realmente vale?",
      sub: "Milhares de criadores usam a Forevault para planejar conteúdo com base em dados reais de receita — não em chute.",
      cta_primary: { label: "Calcular grátis", href: "/youtube-revenue-calculator" },
      cta_secondary: { label: "Ver todos os nichos", href: "/niches" },
      trust: ["Sem cadastro", "100% grátis", "Atualizado mensalmente"],
    },
    MOCKUP: {
      url: "forevault.ink/youtube-revenue-calculator",
      badge: "YouTube",
      title: "Calculadora de receita",
      fields: [
        { label: "Views", val: "1.000.000" },
        { label: "Nicho", val: "AI Tools ▾", hl: true },
        { label: "País", val: "Estados Unidos ▾" },
        { label: "Duração", val: "12m 30s" },
      ],
      button: "Calcular ganhos →",
      resultLabel: "Ganhos estimados",
      resultValue: "US$ 13.850",
      resultAvg: "Média geral: US$ 4.210",
      meta: [
        { k: "RPM", v: "US$ 13,85" },
        { k: "Formato", v: "Long form" },
        { k: "Anúncios", v: "1 mid-roll", hl: true },
      ],
      chartTitle: "Comparação de nichos",
      bars: [
        { label: "AI Tools", pct: 100, active: true },
        { label: "Finance", pct: 78 },
        { label: "Business", pct: 70 },
        { label: "True Crime", pct: 38 },
        { label: "Gaming", pct: 18 },
      ],
      heroEarnings: {
        label: "Ganhos estimados",
        value: "US$ 13.850",
        chips: ["AI Tools", "Estados Unidos"],
      },
      heroNiche: {
        label: "Comparação de RPM por nicho",
        rows: [
          { name: "AI Tools", pct: 100, val: "US$ 13,5" },
          { name: "Business", pct: 78, val: "US$ 10,5" },
          { name: "Gaming", pct: 19, val: "US$ 2,5" },
        ],
      },
      heroRPM: {
        label: "RPM efetivo",
        value: "US$ 13,85",
        sub: "EUA · multiplicador ×2,20",
      },
    },
  },
};

export function getHomeContent(lang) {
  return homeContent[lang] || homeContent.en;
}