export const privacyPages = {
  en: {
    meta: {
      title: "Privacy Policy — Forevault.ink",
      description: "Learn how Forevault.ink handles your data, what we collect, and your rights as a user.",
    },
    backLabel: "Back to Forevault",
    hero: { badge: "Legal", title: "Privacy Policy", meta: "Effective date: January 1, 2026 · Last updated: March 2026" },
    sections: [
      { num: "01", title: "Introduction & Commitment", blocks: [{ type: "text", value: "Forevault.ink is committed to protecting your privacy. This Privacy Policy explains what information we collect (and what we do not), how it is used, and what rights you have regarding your data when you visit or use our Service." }, { type: "text", value: "This policy is written in plain English because we believe everyone has the right to understand how their data is handled — not just lawyers." }] },
      { num: "02", title: "Data We Do Not Collect", blocks: [{ type: "text", value: "Forevault.ink does <strong>not</strong> collect, store, or process any personally identifiable information (PII). There are no user accounts, no registration forms, and no database of personal records. Specifically:" }, { type: "list", items: ["We do not collect your name, email address, or phone number", "We do not store the values you enter into the calculator", "We do not build user profiles or track individual users across sessions", "We do not sell, rent, or trade any user data to third parties"] }, { type: "note", value: "All calculations happen entirely in your browser. No form data is transmitted to our servers." }] },
      { num: "03", title: "Analytics & Usage Data", blocks: [{ type: "text", value: "To understand how visitors interact with the Service and to improve the user experience, we use the following analytics tools:" }, { type: "list", items: ["<strong>Google Analytics (GA4)</strong> — collects anonymised usage data such as page views, session duration, device type, and approximate geographic region. IP addresses are anonymised before storage.", "<strong>Vercel Analytics</strong> — provides lightweight, privacy-friendly performance metrics (load times, error rates) without tracking individual users."] }, { type: "text", value: 'These tools collect data in aggregate. We cannot identify you personally from analytics data. You can opt out of Google Analytics tracking by installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">Google Analytics Opt-out Browser Add-on</a>.' }] },
      { num: "04", title: "Cookies", blocks: [{ type: "text", value: "Forevault.ink uses cookies to improve the browsing experience and deliver relevant advertising. Cookies are small text files stored in your browser. We use the following categories:" }, { type: "list", items: ["<strong>Essential cookies</strong> — required for basic site functionality. These cannot be disabled without affecting core features.", "<strong>Analytics cookies</strong> — set by Google Analytics to track aggregated usage patterns. These are anonymised and do not identify individuals.", "<strong>Advertising cookies</strong> — set by Google AdSense and other ad networks to serve contextually relevant ads. These may track your browsing behaviour across websites."] }, { type: "text", value: "You can manage or disable cookies at any time through your browser settings. Note that disabling certain cookies may affect your experience on this and other websites. Refer to your browser's help section for instructions:" }, { type: "list", items: ["Chrome: Settings → Privacy and Security → Cookies", "Firefox: Settings → Privacy & Security → Cookies and Site Data", "Safari: Preferences → Privacy → Cookies", "Edge: Settings → Cookies and Site Permissions"] }] },
      { num: "05", title: "Advertising", blocks: [{ type: "text", value: "Forevault.ink may display advertisements served by third-party ad networks, including <strong>Google AdSense</strong>. These networks may use cookies and web beacons to collect data about your visits to this and other websites in order to provide advertisements tailored to your interests." }, { type: "text", value: 'We do not have access to, or control over, the cookies used by third-party advertisers. You can opt out of personalised advertising from Google by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer">Google Ad Settings</a> or the <a href="https://optout.aboutads.info/" target="_blank" rel="noopener noreferrer">Network Advertising Initiative opt-out page</a>.' }, { type: "note", variant: "warn", value: "Forevault.ink is an independent tool. While the core calculator is free to use, the standalone website includes third-party advertising (Google AdSense) to support development, hosting costs, and future updates." }] },
      { num: "06", title: "Third-Party Services", blocks: [{ type: "text", value: "The Service may contain links to or integrate with third-party services (e.g. YouTube, social media platforms). This Privacy Policy does not apply to those third-party services. We encourage you to read their respective privacy policies before interacting with them." }, { type: "text", value: "Third-party services currently integrated or referenced:" }, { type: "links", items: [{ label: "Google LLC (Analytics, AdSense) —", text: "Google Privacy Policy", href: "https://policies.google.com/privacy" }, { label: "Vercel Inc. (Hosting, Analytics) —", text: "Vercel Privacy Policy", href: "https://vercel.com/legal/privacy-policy" }] }] },
      { num: "07", title: "Your Rights", blocks: [{ type: "text", value: "Depending on your jurisdiction, you may have the following rights regarding your personal data:" }, { type: "list", items: ["<strong>Right of access</strong> — request a copy of data held about you", "<strong>Right to erasure</strong> — request deletion of any data associated with you", "<strong>Right to object</strong> — object to processing of your data for certain purposes", "<strong>Right to restrict processing</strong> — request that processing be limited", "<strong>Right to data portability</strong> — receive your data in a portable format"] }, { type: "text", value: "As Forevault.ink does not collect personally identifiable information, most of these rights have limited practical application. However, if you believe we hold data about you or have concerns about how your data is processed, please contact us." }] },
      { num: "08", title: "Contact", blocks: [{ type: "text", value: "For any questions, concerns, or requests relating to this Privacy Policy or your personal data, please reach out through the official Forevault social media channels. We aim to respond to all privacy enquiries within 14 business days." }] },
      { num: "09", title: "Changes to This Policy", blocks: [{ type: "text", value: "We reserve the right to update this Privacy Policy at any time. Changes will be effective immediately upon posting to the Service with an updated effective date. We encourage you to review this page periodically. Your continued use of the Service after any changes constitutes your acceptance of the updated policy." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — All rights reserved", updated: "Last updated March 2026" },
  },

  fr: {
    meta: { title: "Politique de confidentialité — Forevault.ink", description: "Découvrez comment Forevault.ink traite vos données, ce que nous collectons et vos droits en tant qu'utilisateur." },
    backLabel: "Retour à Forevault",
    hero: { badge: "Légal", title: "Politique de confidentialité", meta: "Date d'entrée en vigueur : 1er janvier 2026 · Dernière mise à jour : mars 2026" },
    sections: [
      { num: "01", title: "Introduction et engagement", blocks: [{ type: "text", value: "Forevault.ink s'engage à protéger votre vie privée. Cette politique de confidentialité explique quelles informations nous collectons (et lesquelles nous ne collectons pas), comment elles sont utilisées et quels droits vous avez." }, { type: "text", value: "Cette politique est rédigée en langage clair, car nous pensons que tout le monde a le droit de comprendre comment ses données sont traitées." }] },
      { num: "02", title: "Données que nous ne collectons pas", blocks: [{ type: "text", value: "Forevault.ink ne collecte, ne stocke et ne traite <strong>aucune</strong> donnée personnellement identifiable (PII). Il n'y a pas de compte utilisateur, pas de formulaire d'inscription. En particulier :" }, { type: "list", items: ["Nous ne collectons pas votre nom, votre adresse e-mail ni votre numéro de téléphone", "Nous ne stockons pas les valeurs que vous saisissez dans le calculateur", "Nous ne créons pas de profils utilisateurs et ne suivons pas les utilisateurs", "Nous ne vendons, ne louons et n'échangeons aucune donnée utilisateur"] }, { type: "note", value: "Tous les calculs s'effectuent entièrement dans votre navigateur. Aucune donnée n'est transmise à nos serveurs." }] },
      { num: "03", title: "Analytique et données d'utilisation", blocks: [{ type: "text", value: "Nous utilisons Google Analytics (GA4) pour des données anonymisées, et Vercel Analytics pour des métriques légères et respectueuses de la vie privée." }, { type: "text", value: 'Vous pouvez vous désinscrire de Google Analytics en installant le module <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">Google Analytics Opt-out Browser Add-on</a>.' }] },
      { num: "04", title: "Cookies", blocks: [{ type: "text", value: "Forevault.ink utilise des cookies essentiels, d'analyse (Google Analytics) et publicitaires (Google AdSense). Vous pouvez les gérer via les paramètres de votre navigateur." }, { type: "list", items: ["Chrome : Paramètres → Confidentialité et sécurité → Cookies", "Firefox : Paramètres → Vie privée et sécurité", "Safari : Préférences → Confidentialité → Cookies", "Edge : Paramètres → Cookies et autorisations de site"] }] },
      { num: "05", title: "Publicité", blocks: [{ type: "text", value: "Forevault.ink peut afficher des annonces via <strong>Google AdSense</strong>. Vous pouvez désactiver la publicité personnalisée via <a href=\"https://www.google.com/settings/ads\" target=\"_blank\" rel=\"noopener noreferrer\">Google Ad Settings</a>." }, { type: "note", variant: "warn", value: "Forevault.ink est un outil indépendant. Le calculateur est gratuit, mais inclut de la publicité tierce pour soutenir le développement." }] },
      { num: "06", title: "Services tiers", blocks: [{ type: "text", value: "Le Service peut contenir des liens vers des services tiers. Cette politique ne s'applique pas à ces services." }, { type: "links", items: [{ label: "Google LLC —", text: "Politique de confidentialité Google", href: "https://policies.google.com/privacy" }, { label: "Vercel Inc. —", text: "Politique de confidentialité Vercel", href: "https://vercel.com/legal/privacy-policy" }] }] },
      { num: "07", title: "Vos droits", blocks: [{ type: "text", value: "Selon votre juridiction, vous pouvez disposer des droits d'accès, d'effacement, d'opposition, de limitation et de portabilité de vos données personnelles." }] },
      { num: "08", title: "Contact", blocks: [{ type: "text", value: "Pour toute question concernant cette politique, contactez-nous via les canaux sociaux officiels de Forevault. Nous visons à répondre sous 14 jours ouvrables." }] },
      { num: "09", title: "Modifications", blocks: [{ type: "text", value: "Nous nous réservons le droit de mettre à jour cette politique à tout moment. La poursuite de l'utilisation vaut acceptation de la politique mise à jour." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Tous droits réservés", updated: "Dernière mise à jour mars 2026" },
  },

  es: {
    meta: { title: "Política de privacidad — Forevault.ink", description: "Descubre cómo Forevault.ink maneja tus datos, qué recopilamos y tus derechos como usuario." },
    backLabel: "Volver a Forevault",
    hero: { badge: "Legal", title: "Política de privacidad", meta: "Fecha de entrada en vigor: 1 de enero de 2026 · Última actualización: marzo de 2026" },
    sections: [
      { num: "01", title: "Introducción y compromiso", blocks: [{ type: "text", value: "Forevault.ink está comprometido con la protección de tu privacidad. Esta Política explica qué información recopilamos, cómo se usa y qué derechos tienes." }] },
      { num: "02", title: "Datos que no recopilamos", blocks: [{ type: "text", value: "Forevault.ink <strong>no</strong> recopila, almacena ni procesa información personal identificable (PII). No hay cuentas de usuario." }, { type: "list", items: ["No recopilamos tu nombre, correo electrónico ni número de teléfono", "No almacenamos los valores que introduces en la calculadora", "No creamos perfiles de usuario", "No vendemos datos de usuarios a terceros"] }, { type: "note", value: "Todos los cálculos se realizan en tu navegador. Ningún dato se transmite a nuestros servidores." }] },
      { num: "03", title: "Analítica", blocks: [{ type: "text", value: "Usamos Google Analytics (GA4) con datos anonimizados y Vercel Analytics para métricas de rendimiento sin rastreo individual." }] },
      { num: "04", title: "Cookies", blocks: [{ type: "text", value: "Usamos cookies esenciales, de analítica y publicitarias. Puedes gestionarlas en la configuración de tu navegador." }] },
      { num: "05", title: "Publicidad", blocks: [{ type: "text", value: "Forevault.ink puede mostrar anuncios de <strong>Google AdSense</strong>. Puedes desactivar la publicidad personalizada en <a href=\"https://www.google.com/settings/ads\" target=\"_blank\" rel=\"noopener noreferrer\">Google Ad Settings</a>." }, { type: "note", variant: "warn", value: "Forevault.ink es independiente. La calculadora es gratuita pero incluye publicidad de terceros para cubrir costes de desarrollo." }] },
      { num: "06", title: "Servicios de terceros", blocks: [{ type: "text", value: "El Servicio puede incluir enlaces a terceros. Esta política no se aplica a esos servicios." }, { type: "links", items: [{ label: "Google LLC —", text: "Política de privacidad de Google", href: "https://policies.google.com/privacy" }, { label: "Vercel Inc. —", text: "Política de privacidad de Vercel", href: "https://vercel.com/legal/privacy-policy" }] }] },
      { num: "07", title: "Tus derechos", blocks: [{ type: "text", value: "Según tu jurisdicción, tienes derechos de acceso, supresión, oposición, limitación y portabilidad de datos." }] },
      { num: "08", title: "Contacto", blocks: [{ type: "text", value: "Contáctanos por los canales oficiales de Forevault. Respondemos en 14 días laborables." }] },
      { num: "09", title: "Cambios en esta política", blocks: [{ type: "text", value: "Nos reservamos el derecho de actualizar esta política. El uso continuado constituye aceptación." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Todos los derechos reservados", updated: "Última actualización marzo de 2026" },
  },

  de: {
    meta: { title: "Datenschutzerklärung — Forevault.ink", description: "Erfahre, wie Forevault.ink mit deinen Daten umgeht, was wir erfassen und welche Rechte du hast." },
    backLabel: "Zurück zu Forevault",
    hero: { badge: "Rechtliches", title: "Datenschutzerklärung", meta: "Wirksam ab: 1. Januar 2026 · Zuletzt aktualisiert: März 2026" },
    sections: [
      { num: "01", title: "Einleitung & Verpflichtung", blocks: [{ type: "text", value: "Forevault.ink verpflichtet sich zum Schutz deiner Privatsphäre. Diese Datenschutzerklärung erklärt, welche Informationen wir erfassen und welche Rechte du hast." }] },
      { num: "02", title: "Daten, die wir nicht erfassen", blocks: [{ type: "text", value: "Forevault.ink erfasst, speichert oder verarbeitet <strong>keine</strong> personenbezogenen Daten (PII). Es gibt keine Nutzerkonten." }, { type: "list", items: ["Wir erfassen weder Name, E-Mail noch Telefonnummer", "Wir speichern nicht die Werte, die du im Rechner eingibst", "Wir erstellen keine Nutzerprofile", "Wir verkaufen keine Nutzerdaten an Dritte"] }, { type: "note", value: "Alle Berechnungen finden vollständig in deinem Browser statt. Keine Formulardaten werden an unsere Server gesendet." }] },
      { num: "03", title: "Analytics & Nutzungsdaten", blocks: [{ type: "text", value: "Wir verwenden Google Analytics (GA4) mit anonymisierten Daten und Vercel Analytics für datenschutzfreundliche Leistungsmetriken." }] },
      { num: "04", title: "Cookies", blocks: [{ type: "text", value: "Wir verwenden essenzielle, Analyse- und Werbe-Cookies. Du kannst sie über die Einstellungen deines Browsers verwalten." }] },
      { num: "05", title: "Werbung", blocks: [{ type: "text", value: "Forevault.ink kann Anzeigen über <strong>Google AdSense</strong> anzeigen. Du kannst personalisierte Werbung über <a href=\"https://www.google.com/settings/ads\" target=\"_blank\" rel=\"noopener noreferrer\">Google Ad Settings</a> deaktivieren." }, { type: "note", variant: "warn", value: "Forevault.ink ist ein unabhängiges Tool. Der Rechner ist kostenlos, die Website enthält jedoch Werbung, um Entwicklung und Hosting zu finanzieren." }] },
      { num: "06", title: "Dienste von Drittanbietern", blocks: [{ type: "text", value: "Der Service kann Links zu Dritten enthalten. Diese Erklärung gilt nicht für diese Dienste." }, { type: "links", items: [{ label: "Google LLC —", text: "Google Datenschutzerklärung", href: "https://policies.google.com/privacy" }, { label: "Vercel Inc. —", text: "Vercel Datenschutzerklärung", href: "https://vercel.com/legal/privacy-policy" }] }] },
      { num: "07", title: "Deine Rechte", blocks: [{ type: "text", value: "Je nach Rechtsraum hast du das Recht auf Auskunft, Löschung, Widerspruch, Einschränkung und Datenübertragbarkeit." }] },
      { num: "08", title: "Kontakt", blocks: [{ type: "text", value: "Bitte wende dich über die offiziellen Forevault-Kanäle an uns. Wir antworten innerhalb von 14 Werktagen." }] },
      { num: "09", title: "Änderungen an dieser Richtlinie", blocks: [{ type: "text", value: "Wir behalten uns das Recht vor, diese Erklärung jederzeit zu aktualisieren. Die fortgesetzte Nutzung gilt als Zustimmung." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Alle Rechte vorbehalten", updated: "Zuletzt aktualisiert März 2026" },
  },

  pt: {
    meta: { title: "Política de Privacidade — Forevault.ink", description: "Saiba como o Forevault.ink lida com seus dados, o que coletamos e seus direitos como usuário." },
    backLabel: "Voltar ao Forevault",
    hero: { badge: "Legal", title: "Política de Privacidade", meta: "Data de vigência: 1º de janeiro de 2026 · Última atualização: março de 2026" },
    sections: [
      { num: "01", title: "Introdução e compromisso", blocks: [{ type: "text", value: "O Forevault.ink está comprometido em proteger sua privacidade. Esta Política explica quais informações coletamos e quais direitos você tem." }] },
      { num: "02", title: "Dados que não coletamos", blocks: [{ type: "text", value: "O Forevault.ink <strong>não</strong> coleta, armazena ou processa informações pessoais identificáveis (PII). Não há contas de usuário." }, { type: "list", items: ["Não coletamos nome, e-mail ou número de telefone", "Não armazenamos os valores inseridos na calculadora", "Não criamos perfis de usuário", "Não vendemos dados a terceiros"] }, { type: "note", value: "Todos os cálculos acontecem no seu navegador. Nenhum dado é enviado aos nossos servidores." }] },
      { num: "03", title: "Análises e dados de uso", blocks: [{ type: "text", value: "Usamos Google Analytics (GA4) com dados anonimizados e Vercel Analytics para métricas de desempenho respeitosas à privacidade." }] },
      { num: "04", title: "Cookies", blocks: [{ type: "text", value: "Usamos cookies essenciais, de análise e de publicidade. Você pode gerenciá-los nas configurações do navegador." }] },
      { num: "05", title: "Publicidade", blocks: [{ type: "text", value: "O Forevault.ink pode exibir anúncios do <strong>Google AdSense</strong>. Você pode desativar a publicidade personalizada em <a href=\"https://www.google.com/settings/ads\" target=\"_blank\" rel=\"noopener noreferrer\">Google Ad Settings</a>." }, { type: "note", variant: "warn", value: "O Forevault.ink é independente. A calculadora é gratuita, mas o site inclui publicidade de terceiros para apoiar o desenvolvimento." }] },
      { num: "06", title: "Serviços de terceiros", blocks: [{ type: "text", value: "O Serviço pode conter links para terceiros. Esta política não se aplica a esses serviços." }, { type: "links", items: [{ label: "Google LLC —", text: "Política de Privacidade do Google", href: "https://policies.google.com/privacy" }, { label: "Vercel Inc. —", text: "Política de Privacidade da Vercel", href: "https://vercel.com/legal/privacy-policy" }] }] },
      { num: "07", title: "Seus direitos", blocks: [{ type: "text", value: "Dependendo da sua jurisdição, você tem direitos de acesso, exclusão, oposição, limitação e portabilidade de dados." }] },
      { num: "08", title: "Contato", blocks: [{ type: "text", value: "Entre em contato pelos canais oficiais do Forevault. Respondemos em até 14 dias úteis." }] },
      { num: "09", title: "Alterações nesta política", blocks: [{ type: "text", value: "Reservamo-nos o direito de atualizar esta política. O uso contínuo constitui aceitação." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Todos os direitos reservados", updated: "Última atualização março de 2026" },
  },

  ja: {
    meta: { title: "プライバシーポリシー — Forevault.ink", description: "Forevault.inkがあなたのデータをどのように扱うか、何を収集するか、ユーザーとしての権利について説明します。" },
    backLabel: "Forevaultに戻る",
    hero: { badge: "法的事項", title: "プライバシーポリシー", meta: "発効日：2026年1月1日 · 最終更新：2026年3月" },
    sections: [
      { num: "01", title: "はじめに", blocks: [{ type: "text", value: "Forevault.inkはあなたのプライバシーを保護することを約束します。このポリシーは、私たちが収集する情報（および収集しない情報）、その使用方法、およびサービスを訪問または使用する際のデータに関する権利について説明します。" }, { type: "text", value: "このポリシーは平易な言葉で書かれています。データの扱い方を誰もが理解できるべきだと考えているからです。" }] },
      { num: "02", title: "収集しないデータ", blocks: [{ type: "text", value: "Forevault.inkは個人識別情報（PII）を収集、保存、または処理<strong>しません</strong>。ユーザーアカウント、登録フォーム、個人記録のデータベースはありません。" }, { type: "list", items: ["お名前、メールアドレス、電話番号は収集しません", "計算機に入力した値は保存しません", "ユーザープロファイルを作成したり、セッションをまたいでユーザーを追跡したりしません", "ユーザーデータを第三者に販売、賃貸、取引しません"] }, { type: "note", value: "すべての計算はブラウザ内で完全に行われます。フォームデータはサーバーに送信されません。" }] },
      { num: "03", title: "アナリティクスと使用データ", blocks: [{ type: "text", value: "サービスの改善のため、Google Analytics（GA4）による匿名化された使用データとVercel Analyticsによる軽量なパフォーマンス指標を使用しています。" }] },
      { num: "04", title: "クッキー", blocks: [{ type: "text", value: "必須クッキー、分析クッキー（Google Analytics）、広告クッキー（Google AdSense）を使用しています。ブラウザの設定からいつでも管理できます。" }] },
      { num: "05", title: "広告", blocks: [{ type: "text", value: "Forevault.inkは<strong>Google AdSense</strong>を含む第三者広告ネットワークの広告を表示する場合があります。パーソナライズ広告は<a href=\"https://www.google.com/settings/ads\" target=\"_blank\" rel=\"noopener noreferrer\">Google広告設定</a>からオプトアウトできます。" }, { type: "note", variant: "warn", value: "Forevault.inkは独立したツールです。計算機は無料ですが、開発・ホスティングの費用をサポートするために第三者広告（Google AdSense）が含まれています。" }] },
      { num: "06", title: "第三者サービス", blocks: [{ type: "text", value: "サービスには第三者サービスへのリンクが含まれる場合があります。このポリシーはそれらには適用されません。" }, { type: "links", items: [{ label: "Google LLC —", text: "Googleプライバシーポリシー", href: "https://policies.google.com/privacy" }, { label: "Vercel Inc. —", text: "Vercelプライバシーポリシー", href: "https://vercel.com/legal/privacy-policy" }] }] },
      { num: "07", title: "あなたの権利", blocks: [{ type: "text", value: "お住まいの地域によって、アクセス権、消去権、異議申し立て権、処理制限権、データポータビリティ権などの権利をお持ちの場合があります。" }] },
      { num: "08", title: "お問い合わせ", blocks: [{ type: "text", value: "プライバシーポリシーに関するご質問は、Forevaultの公式ソーシャルメディアチャンネルよりお問い合わせください。14営業日以内に回答いたします。" }] },
      { num: "09", title: "ポリシーの変更", blocks: [{ type: "text", value: "このプライバシーポリシーはいつでも更新する権利を留保します。変更後もサービスを継続して利用することで、更新されたポリシーへの同意とみなします。" }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — 全著作権所有", updated: "最終更新：2026年3月" },
  },

  ko: {
    meta: { title: "개인정보 처리방침 — Forevault.ink", description: "Forevault.ink가 귀하의 데이터를 처리하는 방법, 수집 내용 및 사용자로서의 권리에 대해 알아보세요." },
    backLabel: "Forevault로 돌아가기",
    hero: { badge: "법적 고지", title: "개인정보 처리방침", meta: "발효일: 2026년 1월 1일 · 최종 업데이트: 2026년 3월" },
    sections: [
      { num: "01", title: "소개 및 약속", blocks: [{ type: "text", value: "Forevault.ink는 귀하의 개인정보 보호를 위해 최선을 다합니다. 이 개인정보 처리방침은 수집하는 정보(및 수집하지 않는 정보), 사용 방법, 서비스 이용 시 데이터에 관한 권리를 설명합니다." }, { type: "text", value: "이 방침은 누구나 데이터 처리 방식을 이해할 수 있도록 명확한 언어로 작성되었습니다." }] },
      { num: "02", title: "수집하지 않는 데이터", blocks: [{ type: "text", value: "Forevault.ink는 개인 식별 정보(PII)를 수집, 저장 또는 처리<strong>하지 않습니다</strong>. 사용자 계정, 등록 양식 또는 개인 기록 데이터베이스가 없습니다." }, { type: "list", items: ["이름, 이메일 주소 또는 전화번호를 수집하지 않습니다", "계산기에 입력한 값을 저장하지 않습니다", "사용자 프로필을 구축하거나 세션 간 개별 사용자를 추적하지 않습니다", "사용자 데이터를 제3자에게 판매, 임대 또는 거래하지 않습니다"] }, { type: "note", value: "모든 계산은 브라우저에서 완전히 이루어집니다. 양식 데이터는 서버로 전송되지 않습니다." }] },
      { num: "03", title: "분석 및 사용 데이터", blocks: [{ type: "text", value: "서비스 개선을 위해 Google Analytics(GA4)의 익명화된 사용 데이터와 Vercel Analytics의 경량 성능 지표를 사용합니다." }] },
      { num: "04", title: "쿠키", blocks: [{ type: "text", value: "필수 쿠키, 분석 쿠키(Google Analytics), 광고 쿠키(Google AdSense)를 사용합니다. 브라우저 설정에서 언제든지 관리할 수 있습니다." }] },
      { num: "05", title: "광고", blocks: [{ type: "text", value: "Forevault.ink는 <strong>Google AdSense</strong>를 포함한 제3자 광고 네트워크의 광고를 표시할 수 있습니다. <a href=\"https://www.google.com/settings/ads\" target=\"_blank\" rel=\"noopener noreferrer\">Google 광고 설정</a>에서 개인화 광고를 거부할 수 있습니다." }, { type: "note", variant: "warn", value: "Forevault.ink는 독립적인 도구입니다. 계산기는 무료이지만, 개발 및 호스팅을 지원하기 위해 제3자 광고(Google AdSense)가 포함되어 있습니다." }] },
      { num: "06", title: "제3자 서비스", blocks: [{ type: "text", value: "서비스에는 제3자 서비스에 대한 링크가 포함될 수 있습니다. 이 방침은 해당 서비스에는 적용되지 않습니다." }, { type: "links", items: [{ label: "Google LLC —", text: "Google 개인정보 처리방침", href: "https://policies.google.com/privacy" }, { label: "Vercel Inc. —", text: "Vercel 개인정보 처리방침", href: "https://vercel.com/legal/privacy-policy" }] }] },
      { num: "07", title: "귀하의 권리", blocks: [{ type: "text", value: "귀하의 관할권에 따라 접근권, 삭제권, 이의 제기권, 처리 제한권, 데이터 이동권 등의 권리를 가질 수 있습니다." }] },
      { num: "08", title: "연락처", blocks: [{ type: "text", value: "이 방침에 관한 문의사항은 Forevault의 공식 소셜 미디어 채널을 통해 연락해 주세요. 14영업일 이내에 답변드리겠습니다." }] },
      { num: "09", title: "방침 변경", blocks: [{ type: "text", value: "이 개인정보 처리방침은 언제든지 업데이트할 권리를 보유합니다. 변경 후 서비스를 계속 이용하면 업데이트된 방침에 동의한 것으로 간주됩니다." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — 모든 권리 보유", updated: "최종 업데이트: 2026년 3월" },
  },
};

export function getPrivacyPageContent(lang) {
  return privacyPages[lang] || privacyPages.en;
}