export const termsPages = {
  en: {
    meta: { title: "Terms of Use — Forevault.ink", description: "Read the Terms of Use for Forevault.ink, including accuracy disclaimers, liability limitations, and intellectual property rights." },
    backLabel: "Back to Forevault",
    hero: { badge: "Legal", title: "Terms of Use", meta: "Effective date: January 1, 2026 · Last updated: March 2026" },
    sections: [
      { num: "01", title: "Purpose & Scope", blocks: [{ type: "text", value: "Forevault.ink provides a YouTube revenue simulation tool based on estimated RPM figures, niche benchmarks, geographic multipliers, and engagement data. By accessing or using the Service, you agree to be bound by these Terms of Use in their entirety." }, { type: "text", value: "These Terms apply to all visitors, users, and anyone who accesses or uses the Service." }] },
      { num: "02", title: "Accuracy of Estimates", blocks: [{ type: "text", value: "All revenue figures, RPM values, and projections generated by Forevault.ink are <strong>purely indicative estimates</strong> and do not constitute financial advice, guaranteed earnings, or contractual commitments of any kind." }, { type: "list", items: ["Audience demographics, device type, and geographic location", "Advertiser demand and seasonal fluctuations (Q4 vs Q1)", "Content category, brand suitability, and monetisation eligibility", "YouTube's proprietary algorithm and policy changes", "Ad-blocker usage among your audience", "YouTube Premium subscriber views and their revenue share"] }, { type: "note", variant: "warn", icon: "⚠️", value: "Do not use Forevault.ink estimates to make significant financial decisions without consulting verified earnings data from your own YouTube Studio analytics." }] },
      { num: "03", title: "Limitation of Liability", blocks: [{ type: "text", value: "To the fullest extent permitted by applicable law, Forevault.ink, its creator, and any affiliated parties shall not be liable for any discrepancy between estimated figures and actual revenue, or any direct, indirect, incidental, or consequential damages." }, { type: "text", value: "The user assumes full responsibility for any decisions made based on information provided by the Service." }] },
      { num: "04", title: "Intellectual Property", blocks: [{ type: "text", value: "All content, design elements, source code, algorithms, written copy, visual identity, and branding associated with Forevault.ink are the <strong>exclusive intellectual property</strong> of the creator. All rights are reserved." }, { type: "list", items: ["You may not reproduce, copy, adapt, distribute, sell, or create derivative works without prior written consent", "The RPM estimation methodology and weighting algorithm are proprietary and may not be reverse-engineered", "The Forevault name, logo, and visual identity may not be used commercially without permission"] }] },
      { num: "05", title: "Acceptable Use", blocks: [{ type: "text", value: "You agree not to scrape data at scale, introduce malware, misrepresent Forevault.ink estimates as official YouTube data, or generate content that could mislead or harm third parties." }] },
      { num: "06", title: "Modifications to Terms", blocks: [{ type: "text", value: "Forevault.ink reserves the right to modify these Terms at any time without prior notice. Continued use constitutes acceptance of the revised Terms." }] },
      { num: "07", title: "Governing Law", blocks: [{ type: "text", value: "These Terms shall be governed by the laws of France. Any disputes shall be subject to the exclusive jurisdiction of the competent courts of France." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — All rights reserved", updated: "Last updated March 2026" },
  },

  fr: {
    meta: { title: "Conditions d'utilisation — Forevault.ink", description: "Consultez les Conditions d'utilisation de Forevault.ink, incluant les limites de responsabilité et les droits de propriété intellectuelle." },
    backLabel: "Retour à Forevault",
    hero: { badge: "Légal", title: "Conditions d'utilisation", meta: "Date d'entrée en vigueur : 1er janvier 2026 · Dernière mise à jour : mars 2026" },
    sections: [
      { num: "01", title: "Objet et portée", blocks: [{ type: "text", value: "Forevault.ink fournit un outil de simulation de revenus YouTube. En accédant au Service, vous acceptez d'être lié par l'intégralité des présentes Conditions." }] },
      { num: "02", title: "Exactitude des estimations", blocks: [{ type: "text", value: "Toutes les valeurs générées par Forevault.ink sont de <strong>simples estimations indicatives</strong> et ne constituent en aucun cas un conseil financier ou un revenu garanti." }, { type: "note", variant: "warn", icon: "⚠️", value: "N'utilisez pas les estimations de Forevault.ink pour prendre des décisions financières importantes sans consulter les données vérifiées de votre YouTube Studio." }] },
      { num: "03", title: "Limitation de responsabilité", blocks: [{ type: "text", value: "Forevault.ink ne saurait être tenu responsable des différences entre les estimations et les revenus réels, ni de tout dommage direct ou indirect. L'utilisateur assume l'entière responsabilité de ses décisions." }] },
      { num: "04", title: "Propriété intellectuelle", blocks: [{ type: "text", value: "Tout le contenu, code source, algorithmes et branding de Forevault.ink sont la <strong>propriété intellectuelle exclusive</strong> du créateur. Tous droits réservés." }] },
      { num: "05", title: "Utilisation acceptable", blocks: [{ type: "text", value: "Vous vous engagez à ne pas scraper les données, introduire des logiciels malveillants, présenter les estimations comme des données officielles YouTube, ou générer du contenu trompeur." }] },
      { num: "06", title: "Modifications des Conditions", blocks: [{ type: "text", value: "Forevault.ink se réserve le droit de modifier ces Conditions à tout moment. La poursuite de l'utilisation vaut acceptation." }] },
      { num: "07", title: "Droit applicable", blocks: [{ type: "text", value: "Les présentes Conditions sont régies par le droit français. Tout litige sera soumis à la compétence exclusive des juridictions françaises." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Tous droits réservés", updated: "Dernière mise à jour mars 2026" },
  },

  es: {
    meta: { title: "Términos de uso — Forevault.ink", description: "Lee los Términos de uso de Forevault.ink, incluidos los avisos de exactitud, limitaciones de responsabilidad y derechos de propiedad intelectual." },
    backLabel: "Volver a Forevault",
    hero: { badge: "Legal", title: "Términos de uso", meta: "Fecha de entrada en vigor: 1 de enero de 2026 · Última actualización: marzo de 2026" },
    sections: [
      { num: "01", title: "Propósito y alcance", blocks: [{ type: "text", value: "Forevault.ink ofrece una herramienta de simulación de ingresos de YouTube. Al usar el Servicio, aceptas estos Términos en su totalidad." }] },
      { num: "02", title: "Exactitud de las estimaciones", blocks: [{ type: "text", value: "Todas las cifras generadas son <strong>estimaciones meramente indicativas</strong> y no constituyen asesoramiento financiero ni ingresos garantizados." }, { type: "note", variant: "warn", icon: "⚠️", value: "No uses las estimaciones para tomar decisiones financieras importantes sin consultar los datos verificados de tu YouTube Studio." }] },
      { num: "03", title: "Limitación de responsabilidad", blocks: [{ type: "text", value: "Forevault.ink no será responsable de las diferencias entre las estimaciones y los ingresos reales, ni de ningún daño directo o indirecto. El usuario asume toda la responsabilidad." }] },
      { num: "04", title: "Propiedad intelectual", blocks: [{ type: "text", value: "Todo el contenido, código fuente, algoritmos y marca de Forevault.ink son la <strong>propiedad intelectual exclusiva</strong> del creador. Todos los derechos reservados." }] },
      { num: "05", title: "Uso aceptable", blocks: [{ type: "text", value: "Aceptas no extraer datos a gran escala, introducir malware, presentar estimaciones como datos oficiales de YouTube ni generar contenido engañoso." }] },
      { num: "06", title: "Modificaciones de los Términos", blocks: [{ type: "text", value: "Forevault.ink se reserva el derecho de modificar estos Términos en cualquier momento. El uso continuado constituye aceptación." }] },
      { num: "07", title: "Ley aplicable", blocks: [{ type: "text", value: "Estos Términos se rigen por las leyes de Francia. Cualquier disputa estará sujeta a la jurisdicción exclusiva de los tribunales franceses." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Todos los derechos reservados", updated: "Última actualización marzo de 2026" },
  },

  de: {
    meta: { title: "Nutzungsbedingungen — Forevault.ink", description: "Lies die Nutzungsbedingungen von Forevault.ink, einschließlich Genauigkeits-Hinweisen, Haftungsbeschränkungen und geistigen Eigentumsrechten." },
    backLabel: "Zurück zu Forevault",
    hero: { badge: "Rechtliches", title: "Nutzungsbedingungen", meta: "Wirksam ab: 1. Januar 2026 · Zuletzt aktualisiert: März 2026" },
    sections: [
      { num: "01", title: "Zweck & Umfang", blocks: [{ type: "text", value: "Forevault.ink bietet ein YouTube-Einnahmen-Simulationstool. Durch die Nutzung des Services stimmst du diesen Bedingungen vollumfänglich zu." }] },
      { num: "02", title: "Genauigkeit der Schätzungen", blocks: [{ type: "text", value: "Alle generierten Werte sind <strong>rein indikative Schätzungen</strong> und stellen weder Finanzberatung noch garantierte Einnahmen dar." }, { type: "note", variant: "warn", icon: "⚠️", value: "Verwende die Schätzungen nicht für wesentliche finanzielle Entscheidungen ohne Prüfung deiner YouTube-Studio-Daten." }] },
      { num: "03", title: "Haftungsbeschränkung", blocks: [{ type: "text", value: "Forevault.ink haftet nicht für Abweichungen zwischen Schätzungen und tatsächlichen Einnahmen oder für direkte bzw. indirekte Schäden. Der Nutzer trägt die volle Verantwortung." }] },
      { num: "04", title: "Geistiges Eigentum", blocks: [{ type: "text", value: "Alle Inhalte, der Quellcode, Algorithmen und das Branding von Forevault.ink sind <strong>exklusives geistiges Eigentum</strong> des Erstellers. Alle Rechte vorbehalten." }] },
      { num: "05", title: "Erlaubte Nutzung", blocks: [{ type: "text", value: "Du darfst keine Daten scrapen, keine Malware einschleusen, Schätzungen nicht als offizielle YouTube-Daten ausgeben und keine irreführenden Inhalte erstellen." }] },
      { num: "06", title: "Änderungen der Bedingungen", blocks: [{ type: "text", value: "Forevault.ink behält sich das Recht vor, diese Bedingungen jederzeit zu ändern. Die fortgesetzte Nutzung gilt als Zustimmung." }] },
      { num: "07", title: "Anwendbares Recht", blocks: [{ type: "text", value: "Diese Bedingungen unterliegen dem Recht Frankreichs. Streitigkeiten fallen unter die ausschließliche Zuständigkeit der Gerichte Frankreichs." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Alle Rechte vorbehalten", updated: "Zuletzt aktualisiert März 2026" },
  },

  pt: {
    meta: { title: "Termos de Uso — Forevault.ink", description: "Leia os Termos de Uso do Forevault.ink, incluindo avisos de precisão, limitações de responsabilidade e direitos de propriedade intelectual." },
    backLabel: "Voltar ao Forevault",
    hero: { badge: "Legal", title: "Termos de Uso", meta: "Data de vigência: 1º de janeiro de 2026 · Última atualização: março de 2026" },
    sections: [
      { num: "01", title: "Objetivo e escopo", blocks: [{ type: "text", value: "O Forevault.ink fornece uma ferramenta de simulação de receita do YouTube. Ao usar o Serviço, você concorda com estes Termos em sua totalidade." }] },
      { num: "02", title: "Precisão das estimativas", blocks: [{ type: "text", value: "Todos os valores gerados são <strong>estimativas meramente indicativas</strong> e não constituem aconselhamento financeiro nem ganhos garantidos." }, { type: "note", variant: "warn", icon: "⚠️", value: "Não use as estimativas para tomar decisões financeiras importantes sem consultar os dados verificados do seu YouTube Studio." }] },
      { num: "03", title: "Limitação de responsabilidade", blocks: [{ type: "text", value: "O Forevault.ink não é responsável por discrepâncias entre estimativas e receitas reais, nem por danos diretos ou indiretos. O usuário assume total responsabilidade." }] },
      { num: "04", title: "Propriedade intelectual", blocks: [{ type: "text", value: "Todo o conteúdo, código-fonte, algoritmos e branding do Forevault.ink são <strong>propriedade intelectual exclusiva</strong> do criador. Todos os direitos reservados." }] },
      { num: "05", title: "Uso aceitável", blocks: [{ type: "text", value: "Você concorda em não raspar dados em escala, introduzir malware, apresentar estimativas como dados oficiais do YouTube ou gerar conteúdo enganoso." }] },
      { num: "06", title: "Alterações nos Termos", blocks: [{ type: "text", value: "O Forevault.ink reserva-se o direito de modificar estes Termos a qualquer momento. O uso contínuo constitui aceitação." }] },
      { num: "07", title: "Lei aplicável", blocks: [{ type: "text", value: "Estes Termos são regidos pelas leis da França. Quaisquer disputas estarão sujeitas à jurisdição exclusiva dos tribunais franceses." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — Todos os direitos reservados", updated: "Última atualização março de 2026" },
  },

  ja: {
    meta: { title: "利用規約 — Forevault.ink", description: "Forevault.inkの利用規約をお読みください。精度に関する免責事項、責任の制限、知的財産権などが含まれます。" },
    backLabel: "Forevaultに戻る",
    hero: { badge: "法的事項", title: "利用規約", meta: "発効日：2026年1月1日 · 最終更新：2026年3月" },
    sections: [
      { num: "01", title: "目的と適用範囲", blocks: [{ type: "text", value: "Forevault.inkは、推定RPM値、ニッチベンチマーク、地理的乗数、エンゲージメントデータに基づくYouTube収益シミュレーションツールを提供します。サービスにアクセスまたは使用することで、本利用規約全体に同意したことになります。" }] },
      { num: "02", title: "見積もりの精度", blocks: [{ type: "text", value: "Forevault.inkが生成するすべての収益額、RPM値、予測は<strong>純粋に参考の見積もり</strong>であり、財務アドバイス、保証された収益、またはいかなる種類の契約上の約束も構成しません。" }, { type: "note", variant: "warn", icon: "⚠️", value: "YouTube Studioの検証済みデータを確認せずに、Forevault.inkの見積もりを重要な財務的決定に使用しないでください。" }] },
      { num: "03", title: "責任の制限", blocks: [{ type: "text", value: "適用法の許す最大限の範囲で、Forevault.inkはサービスの出力への依存から生じるいかなる損害に対しても責任を負いません。ユーザーはサービスが提供する情報に基づいて行う決定について全責任を負います。" }] },
      { num: "04", title: "知的財産", blocks: [{ type: "text", value: "Forevault.inkに関連するすべてのコンテンツ、デザイン要素、ソースコード、アルゴリズム、テキスト、ビジュアルアイデンティティ、ブランディングは作成者の<strong>独占的知的財産</strong>です。全権利が予約されています。" }] },
      { num: "05", title: "許容される使用", blocks: [{ type: "text", value: "大規模なデータスクレイピング、マルウェアの導入、Forevault.inkの見積もりを公式YouTubeデータとして誤表示すること、または第三者を誤解させたり害を与えたりするコンテンツの生成に使用しないことに同意します。" }] },
      { num: "06", title: "規約の変更", blocks: [{ type: "text", value: "Forevault.inkは、予告なくいつでもこれらの利用規約を変更する権利を留保します。変更後もサービスを継続して使用することで、改訂された規約への同意とみなします。" }] },
      { num: "07", title: "準拠法", blocks: [{ type: "text", value: "本規約はフランス法に準拠します。本規約から生じる紛争はフランスの管轄裁判所の専属管轄に服します。" }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — 全著作権所有", updated: "最終更新：2026年3月" },
  },

  ko: {
    meta: { title: "이용약관 — Forevault.ink", description: "Forevault.ink의 이용약관을 읽어보세요. 정확성 면책 조항, 책임 제한 및 지적 재산권이 포함됩니다." },
    backLabel: "Forevault로 돌아가기",
    hero: { badge: "법적 고지", title: "이용약관", meta: "발효일: 2026년 1월 1일 · 최종 업데이트: 2026년 3월" },
    sections: [
      { num: "01", title: "목적 및 범위", blocks: [{ type: "text", value: "Forevault.ink는 추정 RPM 수치, 틈새 벤치마크, 지역 승수 및 참여도 데이터를 기반으로 YouTube 수익 시뮬레이션 도구를 제공합니다. 서비스에 접근하거나 사용함으로써 본 이용약관 전체에 동의하는 것으로 간주됩니다." }] },
      { num: "02", title: "추정치의 정확성", blocks: [{ type: "text", value: "Forevault.ink가 생성하는 모든 수익 수치, RPM 값 및 예측은 <strong>순전히 참고용 추정치</strong>이며 재무 조언, 보장된 수익 또는 계약상 약정을 구성하지 않습니다." }, { type: "note", variant: "warn", icon: "⚠️", value: "YouTube Studio의 확인된 수익 데이터를 검토하지 않고 Forevault.ink 추정치를 중요한 재무 결정에 사용하지 마십시오." }] },
      { num: "03", title: "책임의 제한", blocks: [{ type: "text", value: "적용 가능한 법률이 허용하는 최대 범위 내에서, Forevault.ink는 서비스 출력에 대한 의존으로 인해 발생하는 어떠한 손해에 대해서도 책임을 지지 않습니다. 사용자는 서비스가 제공하는 정보를 기반으로 내린 결정에 대해 전적인 책임을 집니다." }] },
      { num: "04", title: "지적 재산권", blocks: [{ type: "text", value: "Forevault.ink와 관련된 모든 콘텐츠, 디자인 요소, 소스 코드, 알고리즘, 텍스트, 시각적 아이덴티티 및 브랜딩은 창작자의 <strong>독점적 지적 재산</strong>입니다. 모든 권리가 보유됩니다." }] },
      { num: "05", title: "허용되는 사용", blocks: [{ type: "text", value: "대규모 데이터 스크래핑, 악성 코드 도입, Forevault.ink 추정치를 공식 YouTube 데이터로 오표시하거나 제3자를 오도하거나 해를 끼칠 수 있는 콘텐츠 생성에 서비스를 사용하지 않을 것에 동의합니다." }] },
      { num: "06", title: "약관 수정", blocks: [{ type: "text", value: "Forevault.ink는 사전 통지 없이 언제든지 이용약관을 수정할 권리를 보유합니다. 수정 후 서비스를 계속 사용하면 개정된 약관에 동의한 것으로 간주됩니다." }] },
      { num: "07", title: "준거법", blocks: [{ type: "text", value: "본 약관은 프랑스 법률에 따라 규율됩니다. 본 약관과 관련하여 발생하는 모든 분쟁은 프랑스의 관할 법원의 독점적 관할권에 따릅니다." }] },
    ],
    footer: { copy: "© 2026 Forevault.ink — 모든 권리 보유", updated: "최종 업데이트: 2026년 3월" },
  },
};

export function getTermsPageContent(lang) {
  return termsPages[lang] || termsPages.en;
}