export const countryRPM = [

  // TIER 1 - Premium ad markets
  { id: 'us', name: 'États-Unis', tier: 1, multiplier: 2.20 },
  { id: 'ch', name: 'Suisse', tier: 1, multiplier: 2.00 },
  { id: 'au', name: 'Australie', tier: 1, multiplier: 1.80 },
  { id: 'sg', name: 'Singapour', tier: 1, multiplier: 1.80 },
  { id: 'uk', name: 'Royaume-Uni', tier: 1, multiplier: 1.70 },
  { id: 'ca', name: 'Canada', tier: 1, multiplier: 1.65 },
  { id: 'jp', name: 'Japon', tier: 1, multiplier: 1.60 },
  { id: 'no', name: 'Norvège', tier: 1, multiplier: 1.55 },
  { id: 'dk', name: 'Danemark', tier: 1, multiplier: 1.50 },
  { id: 'se', name: 'Suède', tier: 1, multiplier: 1.45 },
  { id: 'de', name: 'Allemagne', tier: 1, multiplier: 1.40 },
  { id: 'ie', name: 'Irlande', tier: 1, multiplier: 1.35 },
  { id: 'fr', name: 'France', tier: 1, multiplier: 1.00 },

  // TIER 2 - Good advertising markets
  { id: 'nl', name: 'Pays-Bas', tier: 2, multiplier: 1.10 },
  { id: 'kr', name: 'Corée du Sud', tier: 2, multiplier: 1.10 },
  { id: 'ae', name: 'Émirats Arabes Unis', tier: 2, multiplier: 1.25 },
  { id: 'qa', name: 'Qatar', tier: 2, multiplier: 1.20 },
  { id: 'il', name: 'Israël', tier: 2, multiplier: 1.10 },
  { id: 'be', name: 'Belgique', tier: 2, multiplier: 1.05 },
  { id: 'at', name: 'Autriche', tier: 2, multiplier: 1.00 },
  { id: 'es', name: 'Espagne', tier: 2, multiplier: 0.90 },
  { id: 'it', name: 'Italie', tier: 2, multiplier: 0.85 },
  { id: 'nz', name: 'Nouvelle-Zélande', tier: 2, multiplier: 1.20 },

  // TIER 3 - Emerging markets
  { id: 'pl', name: 'Pologne', tier: 3, multiplier: 0.65 },
  { id: 'br', name: 'Brésil', tier: 3, multiplier: 0.50 },
  { id: 'mx', name: 'Mexique', tier: 3, multiplier: 0.50 },
  { id: 'tr', name: 'Turquie', tier: 3, multiplier: 0.45 },
  { id: 'za', name: 'Afrique du Sud', tier: 3, multiplier: 0.55 },
  { id: 'ar', name: 'Argentine', tier: 3, multiplier: 0.40 },
  { id: 'co', name: 'Colombie', tier: 3, multiplier: 0.35 },
  { id: 'ma', name: 'Maroc', tier: 3, multiplier: 0.30 },
  { id: 'dz', name: 'Algérie', tier: 3, multiplier: 0.25 },
  { id: 'tn', name: 'Tunisie', tier: 3, multiplier: 0.25 },
  { id: 'in', name: 'Inde', tier: 3, multiplier: 0.30 },
  { id: 'id', name: 'Indonésie', tier: 3, multiplier: 0.30 },
  { id: 'th', name: 'Thaïlande', tier: 3, multiplier: 0.35 },
  { id: 'ph', name: 'Philippines', tier: 3, multiplier: 0.25 },
  { id: 'vn', name: 'Vietnam', tier: 3, multiplier: 0.20 },
  { id: 'eg', name: 'Égypte', tier: 3, multiplier: 0.20 },
  { id: 'ng', name: 'Nigéria', tier: 3, multiplier: 0.20 }

];


export const niches = [
  {
    id: "rank-01",
    niche: "Rankings / Top 10 (General)",
    topic: "mainstream topics",
    rpm_long: 4.2, // Légèrement baissé pour le général
    rpm_shorts: 0.05,
    faceless: "faceless",
    saturation: 4,
    potentiel_economique: 3,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "rank-02",
    niche: "Rankings / Top 10",
    topic: "luxury & rich lifestyle",
    rpm_long: 7.8,
    rpm_shorts: 0.08,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 4,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "rank-03",
    niche: "Rankings / Top 10",
    topic: "technology & gadgets",
    rpm_long: 9.4,
    rpm_shorts: 0.09,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 4,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: false
  },
  {
    id: "story-01",
    niche: "Storytelling",
    topic: "horror stories",
    rpm_long: 3.5, // L'horreur est souvent "yellow-monetized" (pub limitée)
    rpm_shorts: 0.04,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 3,
    facilite_creation: 5,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "story-02",
    niche: "Storytelling",
    topic: "Reddit stories",
    rpm_long: 3.2,
    rpm_shorts: 0.04,
    faceless: "faceless",
    saturation: 4,
    potentiel_economique: 3,
    facilite_creation: 5,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "story-03",
    niche: "Storytelling",
    topic: "true crime",
    rpm_long: 5.2,
    rpm_shorts: 0.06,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 4,
    facilite_creation: 3,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "story-04",
    niche: "Storytelling",
    topic: "historical stories",
    rpm_long: 6.7,
    rpm_shorts: 0.07,
    faceless: "faceless",
    saturation: 2,
    potentiel_economique: 4,
    facilite_creation: 3,
    popularite: "niché",
    trending: true
  },
  {
    id: "comm-01",
    niche: "Commentary",
    topic: "internet drama",
    rpm_long: 3.8,
    rpm_shorts: 0.04,
    faceless: "not faceless",
    saturation: 5,
    potentiel_economique: 3,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "comm-02",
    niche: "Commentary",
    topic: "food & cooking reactions",
    rpm_long: 5.1,
    rpm_shorts: 0.06,
    faceless: "not faceless",
    saturation: 4,
    potentiel_economique: 3,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: false
  },
  {
    id: "comm-03",
    niche: "Commentary",
    topic: "pets & animals",
    rpm_long: 4.1,
    rpm_shorts: 0.05,
    faceless: "not faceless",
    saturation: 4,
    potentiel_economique: 2,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: false
  },
  {
    id: "doc-01",
    niche: "Mini Documentaries",
    topic: "business & companies",
    rpm_long: 10.5,
    rpm_shorts: 0.10,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 5,
    facilite_creation: 3,
    popularite: "niché",
    trending: true
  },
  {
    id: "doc-02",
    niche: "Mini Documentaries",
    topic: "history",
    rpm_long: 7.4,
    rpm_shorts: 0.07,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 4,
    facilite_creation: 3,
    popularite: "mainstream",
    trending: false
  },
  {
    id: "ice-01",
    niche: "Iceberg Videos",
    topic: "internet mysteries",
    rpm_long: 4.8,
    rpm_shorts: 0.05,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 3,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "edu-01",
    niche: "Educational Explainers",
    topic: "science",
    rpm_long: 7.8,
    rpm_shorts: 0.08,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 4,
    facilite_creation: 3,
    popularite: "mainstream",
    trending: false
  },
  {
    id: "edu-02",
    niche: "Educational Explainers",
    topic: "psychology",
    rpm_long: 8.2,
    rpm_shorts: 0.08,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 4,
    facilite_creation: 3,
    popularite: "niché",
    trending: true
  },
  {
    id: "ai-01",
    niche: "AI Tools",
    topic: "AI tutorials",
    rpm_long: 13.5,
    rpm_shorts: 0.12,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 5,
    facilite_creation: 3,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "ai-02",
    niche: "AI Tools",
    topic: "AI news",
    rpm_long: 10.8,
    rpm_shorts: 0.10,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 5,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "lux-01",
    niche: "Luxury Lifestyle",
    topic: "billionaires & rich lifestyle",
    rpm_long: 7.6,
    rpm_shorts: 0.07,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 4,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: true
  },
  {
    id: "relax-01",
    niche: "Relaxation Content",
    topic: "sleep sounds",
    rpm_long: 2.8, // Très bas car peu d'interaction et d'attention publicitaire
    rpm_shorts: 0.03,
    faceless: "faceless",
    saturation: 2,
    potentiel_economique: 3,
    facilite_creation: 5,
    popularite: "niché",
    trending: true
  },
  {
    id: "game-01",
    niche: "Gaming",
    topic: "gameplay commentary",
    rpm_long: 2.5,
    rpm_shorts: 0.03,
    faceless: "not faceless",
    saturation: 5,
    potentiel_economique: 3,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: false
  },
  {
    id: "game-02",
    niche: "Gaming",
    topic: "game lore & story explained",
    rpm_long: 4.2,
    rpm_shorts: 0.05,
    faceless: "faceless",
    saturation: 3,
    potentiel_economique: 3,
    facilite_creation: 4,
    popularite: "mainstream",
    trending: true
  }
];