"use client";

import { useEffect, useRef } from "react";
import gsap from "gsap";
import "../legal.scss";
import Navbar from "../nav";

const SECTIONS = [
    {
        num:   "01",
        title: "Purpose & Scope",
        content: (
            <>
                <p className="legal-p">
                    Forevault.ink provides a YouTube revenue simulation
                    tool based on estimated RPM (Revenue Per Mille) figures, niche
                    benchmarks, geographic multipliers, and engagement data. By
                    accessing or using the Service, you agree to be bound by these
                    Terms of Use in their entirety.
                </p>
                <p className="legal-p">
                    These Terms apply to all visitors, users, and anyone who accesses
                    or uses the Service. If you do not agree with any part of these
                    Terms, you must discontinue use of the Service immediately.
                </p>
            </>
        ),
    },
    {
        num:   "02",
        title: "Accuracy of Estimates",
        content: (
            <>
                <p className="legal-p">
                    All revenue figures, RPM values, and projections generated by
                    Forevault.ink are{" "}
                    <strong>purely indicative estimates</strong> and do not constitute
                    financial advice, guaranteed earnings, or contractual commitments of
                    any kind.
                </p>
                <p className="legal-p">
                    Real YouTube AdSense earnings are subject to a wide range of
                    variables that cannot be modelled with complete precision, including
                    but not limited to:
                </p>
                <ul className="legal-ul">
                    <li>Audience demographics, device type, and geographic location</li>
                    <li>Advertiser demand and seasonal fluctuations (Q4 vs Q1)</li>
                    <li>Content category, brand suitability, and monetisation eligibility</li>
                    <li>YouTube's proprietary algorithm and policy changes</li>
                    <li>Ad-blocker usage among your audience</li>
                    <li>YouTube Premium subscriber views and their revenue share</li>
                </ul>
                <div className="legal-warn">
                    <span className="legal-warn__icon">⚠️</span>
                    <span>
                        Do not use Forevault.ink estimates to make significant financial
                        decisions, negotiate brand deals, or plan business expenditures
                        without consulting verified earnings data from your own YouTube
                        Studio analytics.
                    </span>
                </div>
            </>
        ),
    },
    {
        num:   "03",
        title: "Limitation of Liability",
        content: (
            <>
                <p className="legal-p">
                    To the fullest extent permitted by applicable law, Forevault.ink,
                    its creator, and any affiliated parties shall not be liable for:
                </p>
                <ul className="legal-ul">
                    <li>
                        Any discrepancy between estimated figures displayed by the
                        Service and actual revenue credited by Google AdSense or
                        YouTube's monetisation system
                    </li>
                    <li>
                        Any direct, indirect, incidental, special, or consequential
                        damages arising from reliance on the Service's output
                    </li>
                    <li>
                        Loss of income, revenue, data, business opportunities, or
                        goodwill resulting from use or inability to use the Service
                    </li>
                    <li>
                        Interruptions, errors, or inaccuracies in the Service caused
                        by technical failures or third-party data providers
                    </li>
                </ul>
                <p className="legal-p">
                    The user assumes full responsibility for any decisions made
                    based on information provided by the Service.
                </p>
            </>
        ),
    },
    {
        num:   "04",
        title: "Intellectual Property",
        content: (
            <>
                <p className="legal-p">
                    All content, design elements, source code, algorithms, written
                    copy, visual identity, and branding associated with Forevault.ink
                    are the <strong>exclusive intellectual property</strong> of the
                    creator. All rights are reserved.
                </p>
                <ul className="legal-ul">
                    <li>
                        You may not reproduce, copy, adapt, distribute, sell, or
                        create derivative works from any part of the Service without
                        prior written consent
                    </li>
                    <li>
                        The RPM estimation methodology and weighting algorithm are
                        proprietary and may not be reverse-engineered or replicated
                    </li>
                    <li>
                        The Forevault name, logo, and visual identity may not be used
                        in any commercial or promotional context without permission
                    </li>
                </ul>
                <div className="legal-note">
                    <span className="legal-note__icon">ℹ️</span>
                    <span>
                        Fair use of factual information from the site for educational
                        or journalistic purposes is permitted provided proper
                        attribution to Forevault.ink is given.
                    </span>
                </div>
            </>
        ),
    },
    {
        num:   "05",
        title: "Acceptable Use",
        content: (
            <>
                <p className="legal-p">
                    You agree not to use the Service for any purpose that is unlawful,
                    abusive, or harmful. Specifically, you agree not to:
                </p>
                <ul className="legal-ul">
                    <li>Attempt to scrape, crawl, or programmatically extract data from the Service at scale</li>
                    <li>Introduce malware, scripts, or code that could damage the Service or its users</li>
                    <li>Misrepresent Forevault.ink's estimates as official YouTube or Google data</li>
                    <li>Use the Service to generate content that could mislead, defraud, or harm third parties</li>
                </ul>
            </>
        ),
    },
    {
        num:   "06",
        title: "Modifications to Terms",
        content: (
            <p className="legal-p">
                Forevault.ink reserves the right to modify these Terms of Use at
                any time without prior notice. Changes will be reflected by the
                updated date at the top of this page. Continued use of the Service
                after modifications constitutes your acceptance of the revised Terms.
                It is your responsibility to review these Terms periodically.
            </p>
        ),
    },
    {
        num:   "07",
        title: "Governing Law",
        content: (
            <p className="legal-p">
                These Terms shall be governed by and construed in accordance with
                the laws of France. Any disputes arising from or in connection
                with these Terms shall be subject to the exclusive jurisdiction
                of the competent courts of France, without regard to conflict of
                law provisions.
            </p>
        ),
    },
];

export default function TermsPage() {
    const boxRef = useRef(null);

    useEffect(() => {
        const ctx = gsap.context(() => {
            gsap.from(boxRef.current, {
                opacity: 0, y: 38, scale: .97,
                duration: .85, ease: "expo.out",
            });
            gsap.from(".legal-section", {
                opacity: 0, y: 12,
                duration: .45, stagger: .06, delay: .4,
                ease: "power2.out",
            });
        }, boxRef);
        return () => ctx.revert();
    }, []);

    return (
        <div className="lg-root">
            <Navbar/>
            <a href="/" className="lg-back">
                <span className="lg-back__arrow">←</span>
                Back to Forevault
            </a>

            <div className="legal-box" ref={boxRef}>

                {/* ── hero band ───────────────────────────────────────────── */}
                <div className="legal-hero">
                    <span className="legal-hero__badge">Legal</span>
                    <h1 className="legal-hero__title">Terms of Use</h1>
                    <p className="legal-hero__meta">
                        Effective date: January 1, 2026 &nbsp;·&nbsp; Last updated: March 2026
                    </p>
                </div>

                {/* ── sections ────────────────────────────────────────────── */}
                <div className="legal-body">
                    {SECTIONS.map((s, i) => (
                        <div key={s.num}>
                            <section className="legal-section">
                                <div className="legal-section__head">
                                    <span className="legal-section__num">{s.num}</span>
                                    <h2 className="legal-section__title">{s.title}</h2>
                                </div>
                                {s.content}
                            </section>
                            {i < SECTIONS.length - 1 && <div className="legal-sep" style={{ marginTop: "2rem" }} />}
                        </div>
                    ))}
                </div>

                <div className="legal-foot">
                    <span className="legal-foot__copy">© 2026 Forevault.ink — All rights reserved</span>
                    <span className="legal-foot__updated">
                        <span />
                        Last updated March 2026
                    </span>
                </div>

            </div>
        </div>
    );
}